#!/bin/bash
echo
echo " Downloading and Setting up Official Blackarch Wallpaper "
wget https://raw.github.com/t60r/blackarch-site/master/images/blackarch-wallpaper-simple.png
sleep 1 &&
mkdir ~/.fehBACK &&
sleep 1 &&
mv blackarch-wallpaper-simple.png ~/.fehBACK/ &&
feh --bg-scale ~/.fehBACK/blackarch-wallpaper-simple.png &&
echo "feh --bg-scale ~/.fehBACK/blackarch-wallpaper-simple.png" > ~/.fehbg &&
echo
echo " Never worry about a wallpaper :)    -- This is for i3-blackarch --look in-- '~/.i3/config' " 
sleep 2 &&
echo "Would you like to remove i3-blackarch directory ?    (Y) or (N) "
read WTFBBQ
if [ "$WTFBBQ" == y -o "$WTFBBQ" == Y ]
	then
		rm -rf $HOME/i3-blackarch
	else
		echo " Understood "
fi
sleep 1 &&
echo " If You installed our custom zsh config (pacaur script) you need to reboot"
echo " For changes to take effect since you are using root"
echo " Do you need to reboot ?      (Y) or (N)  "
read WTFBBQ2
if [ "$WTFBBQ2" == Y -o "$WTFBBQ2" == y ]
	then
		reboot
	else
		echo " Thanks for using i3-blackarch  ! "
fi
