#!/bin/bash
wget https://raw.github.com/t60r/blackarch-site/master/images/blackarch-wallpaper-simple.png
sleep 1 &&
mkdir ~/.fehBACK &&
sleep 1 &&
mv blackarch-wallpaper-simple.png ~/.fehBACK/ &&
feh --bg-scale ~/.fehBACK/blackarch-wallpaper-simple.png &&
echo "feh --bg-scale ~/.fehBACK/blackarch-wallpaper-simple.png" > ~/.fehbg &&
exit
