#!/bin/bash
# By: i3-Arch 
red=$(tput setaf 1)
white=$(tput setaf 7)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
purple=$(tput setaf 4)
CHOICE=4
	until [ $CHOICE -eq 5 ]
	do
clear
	echo
	echo -e "\033[1m ${red} Choose a Menu Item\033[0m"
	echo -e "${white}"
	echo -e " \033[1m ${red}1)${white}\033[1m Show Blackarch Catagories \033[0m"
	echo -e " \033[1m ${red}2)${white}\033[1m Install All Blackarch Packages \033[0m"
	echo -e " \033[1m ${red}3)${white}\033[1m Install Wireless, Cracker, and Exploitation Catagories  \033[0m"
	echo -e " \033[1m ${red}4)${white}\033[1m Show Github for Custom i3-Blackarch Build \033[0m"
	echo -e " \033[1m ${red}5)${white}\033[1m Exit\033[0m"
	echo
read CHOICE
	case $CHOICE in
		1) echo -e "\033[1m ${green} `pacman -Sg |grep blackarch`" ;;
		2) echo -e "\033[1m ${yellow} `pacman -S blackarch`" ;;
		3) echo -e "\033[1m ${yellow} `pacman -S blackarch-wireless blackarch-cracker blackarch-exploitation` " ;;
		4) echo -e "\033[1m ${white} https://github.com/t60r/i3-blackarch" ;;
		5) echo -e "\033[1m ${purple} Thanks for Using i3-Blackarch " ;;
		*) echo -e "\033[1m ${red} invalid option\033[0m"
	esac
echo
	echo -e "\033[1m ${green} Press Enter to Continue\033[0m"
read Enter
	done
