#!/bin/bash
#	THIS IS JUST THE BEGINNING \\ DONT TRIP
# i3-Arch     \\ i3-Blackarch //
#####################################
$(cd $HOME)
$(git clone https://github.com/Blackarch/i3-blackarch.git)
sleep 2
if [ $HOME/i3-blackarch/.scripts-for-setup ]
	then
		cd "${HOME?}/i3-blackarch/.scripts-for-setup"
	else
		echo
		echo " Where is scripts-for-setup  ?? "
fi
echo
source setupX
