#!/bin/bash
# Im new to bash... and still young and learning... so dont hit me .... kthnx
# This builds pacaur, and sets up oh-my-zsh
# i3-Arch    \\ i3-Blackarch //
#################################################
echo " Press Enter to Continue.. "
read ENTER
echo
echo " Using old version of cower to do this.."
echo " I reccomend letting the script remove pacaur + cower later on..."
wget http://pkg.sbr.io/archlinux/i686/cower-git-9.19.gf2d9c48-1-i686.pkg.tar.xz &&
sleep 2 &&
pacman -U *.tar.xz &&
sleep 1 &&
rm *.tar.xz &&
sleep 2 &&
wget https://aur.archlinux.org/packages/pa/pacaur/pacaur.tar.gz &&
sleep 2 &&
tar xzvf pacaur.tar.gz &&
sleep 2 &&
cd pacaur &&
makepkg -s --asroot &&
sleep 2 &&
pacman -U *.tar.xz &&
sleep 3 &&
cd .. &&
rm *.tar.gz &&
rm -rf pacaur &&
sleep 2 &&
	if [ $HOME/.zshrc ]
		then
			$(rm ~/.zshrc)
if [ $HOME/.zlogin ] 
	then
		$(rm ~/.zlogin)
fi
	fi
sleep 1 &&
pacaur -S oh-my-zsh-git --asroot &&
sleep 2 &&
wget https://raw.github.com/i3-Arch/i3config/master/zshrc &&
sleep 1 &&
cp zshrc ~/.zshrc &&
sleep 1 &&
chsh -s $(which zsh) &&
echo " CLOSE OPENED TERMINALS, AND RE-OPEN TO SEE NEW SHELL and SHELL CONFIG ! "
sleep 3 &&
echo
echo " Would you like to remove pacaur + cower now ?     Y or N  "
echo
read QUESTION
	if [ $QUESTION == Y -o $QUESTION == y ]
		then
			$(sudo pacman -R pacaur cower)
		else
			echo
			echo " You Chose NO - OR An Invalid Character Was Entered "
	fi
echo
echo " Report Errors / Tips to i3-Arch @ irc.freenode.net #blackarch "
echo
