#!/bin/bash
# Im new to bash... and still young and learning... so dont hit me .... kthnx
# This builds pacaur, and sets up oh-my-zsh
# i3-Arch    \\ i3-Blackarch //
#################################################
if [ "$(uname -m)" = x86_64 ]
then
	echo -e " Using old version of cower to do this.."
	echo -e " I reccomend letting the script remove pacaur + cower later on..."
	echo -e " BE PATIENT "
	echo -e " $(wget http://pkg.sbr.io/archlinux/x86_64/cower-git-9.19.gf2d9c48-1-x86_64.pkg.tar.xz) "
	pacman -U *.tar.xz --noconfirm
	rm *.tar.xz
	wget https://aur.archlinux.org/packages/pa/pacaur/pacaur.tar.gz
	tar xzvf pacaur.tar.gz
	cd pacaur
	makepkg -s --asroot
	pacman -U *.tar.xz --noconfirm
	cd ..
	rm *.tar.gz
	rm -rf pacaur
	if [ $HOME/.zshrc ]
	then
		$(rm ~/.zshrc)
		if [ $HOME/.zlogin ] 
		then
			$(rm ~/.zlogin)
		fi
	fi
	pacaur -S oh-my-zsh-git --asroot --noconfirm
	pacaur -S urxvt-tabbedex --asroot --noconfirm
	pacaur -S urxvt-vtwheel --asroot --noconfirm
	pacaur -S urxvt-font-size-git --asroot --noconfirm
	wget https://raw.github.com/i3-Arch/i3config/master/zshrc
	cp zshrc ~/.zshrc
	chsh -s $(which zsh)
	echo " Reboot for it to take changes  ! "
	echo " Would you like to remove pacaur + cower now ?     Y or N  "
	read QUESTION
		if [ $QUESTION == Y -o $QUESTION == y ]
			then
				$(pacman -Rs pacaur --noconfirm)
			else
				echo
				echo " You Chose NO - OR An Invalid Character Was Entered "
		fi
	echo " Report Errors / Tips to i3-Arch @ irc.freenode.net #blackarch "
	echo " NOW SETTING UP BACKGROUND  AND REBOOTING INTO NEW SETUP"
	source background-ASAP

elif [ "$(uname -m)" = i686 ]
then
	echo -e " Using old version of cower to do this.."
	echo -e " I reccomend letting the script remove pacaur + cower later on..."
	echo -e " BE PATIENT "
	echo -e " $(wget http://pkg.sbr.io/archlinux/i686/cower-git-9.19.gf2d9c48-1-i686.pkg.tar.xz) "

	pacman -U *.tar.xz --noconfirm
	rm *.tar.xz
	wget https://aur.archlinux.org/packages/pa/pacaur/pacaur.tar.gz &&
	tar xzvf pacaur.tar.gz
	cd pacaur
	makepkg -s --asroot
	pacman -U *.tar.xz --noconfirm
	cd ..
	rm *.tar.gz
	rm -rf pacaur
	if [ $HOME/.zshrc ]
	then
		$(rm ~/.zshrc)
		if [ $HOME/.zlogin ] 
		then
			$(rm ~/.zlogin)
		fi
	fi
	sleep 1
	pacaur -S oh-my-zsh-git --asroot --noconfirm
	pacaur -S urxvt-tabbedex --asroot --noconfirm
	pacaur -S urxvt-vtwheel --asroot --noconfirm
	pacaur -S urxvt-font-size-git --asroot --noconfirm
	sleep 2
	wget https://raw.github.com/i3-Arch/i3config/master/zshrc
	cp zshrc ~/.zshrc
	sleep 1
	chsh -s $(which zsh)
	echo " Reboot for it to take changes  ! "
	echo " Would you like to remove pacaur + cower now ?     Y or N  "
	read QUESTION
		if [ $QUESTION == Y -o $QUESTION == y ]
			then
				$(pacman -Rs pacaur --noconfirm)
			else
				echo
				echo " You Chose NO - OR An Invalid Character Was Entered "
		fi
	echo " Report Errors / Tips to i3-Arch @ irc.freenode.net #blackarch "
	sleep 3
	echo " NOW SETTING UP BACKGROUND  AND REBOOTING INTO NEW SETUP"
	source background-ASAP
fi
