#!/bin/bash
# Im new to bash... and still young and learning... so dont hit me .... kthnx
# This builds pacaur, and sets up oh-my-zsh
# i3-Arch    \\ i3-Blackarch //
#################################################
echo
echo -e " Using old version of cower to do this.."
echo -e " I reccomend letting the script remove pacaur + cower later on..."
echo -e " BE PATIENT "
echo -e " $(wget http://pkg.sbr.io/archlinux/i686/cower-git-9.19.gf2d9c48-1-i686.pkg.tar.xz) "
sleep 2 &&
pacman -U *.tar.xz --noconfirm &&
sleep 1 &&
rm *.tar.xz &&
sleep 2 &&
wget https://aur.archlinux.org/packages/pa/pacaur/pacaur.tar.gz &&
sleep 2 &&
tar xzvf pacaur.tar.gz &&
sleep 2 &&
cd pacaur &&
makepkg -s --asroot &&
sleep 2 &&
pacman -U *.tar.xz --noconfirm &&
sleep 3 &&
cd .. &&
rm *.tar.gz &&
rm -rf pacaur &&
sleep 2 &&
	if [ $HOME/.zshrc ]
		then
			$(rm ~/.zshrc)
if [ $HOME/.zlogin ] 
	then
		$(rm ~/.zlogin)
fi
	fi
sleep 1 &&
pacaur -S oh-my-zsh-git --asroot --noconfirm &&
sleep 2 &&
wget https://raw.github.com/i3-Arch/i3config/master/zshrc &&
sleep 1 &&
cp zshrc ~/.zshrc &&
sleep 1 &&
chsh -s $(which zsh) &&
echo " Reboot for it to take changes  ! "
sleep 3 &&
echo
echo " Would you like to remove pacaur + cower now ?     Y or N  "
echo
read QUESTION
	if [ $QUESTION == Y -o $QUESTION == y ]
		then
			$(sudo pacman -R pacaur cower --noconfirm)
		else
			echo
			echo " You Chose NO - OR An Invalid Character Was Entered "
	fi
echo
echo " Report Errors / Tips to i3-Arch @ irc.freenode.net #blackarch "
echo
echo " Would you like for me to reboot for you ?    'y' or 'n' "
echo
read mewmew
if [ "$mewmew" == y -o "$mewmew" == Y ]
	then
		echo " $(reboot) "
	else
		echo " Thanks for using :: i3-blackarch :: "
fi
