#!/bin/bash 
# i3-Arch        |      Setup X     |   
# t60r	        /|\  i3-BlackArch  /|\
###############################################

# FONT
setfont Lat2-Terminus16

# COLORS
red=$(tput setaf 1)
white=$(tput setaf 7)
green=$(tput setaf 2)
yellow=$(tput setaf 3)

FirstThing() {
	printf "\033[1m\n\n ${green}Updating/Upgrading & Adding UTF-8 locales for i3 setup \n\n\033[0m"
	pacman -Syyu --noconfirm
	echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
	locale-gen
	LANG=en_US.utf8
	printf "\n\033[1m${red}Setting locales system wide.... ${yellow}via /etc/locale.conf\n\n\033[0m"
	locale > /etc/locale.conf
}


PartOne() {
	printf "\033[1m\n\n ${green} Creating User to build AUR packages ( Will remove afterwards ) \n\n\033[0m"
	useradd -m -G adm,disk builder
	su builder -c "cd /home/builder && git clone https://github.com/Blackarch/i3-blackarch.git"
	if [ -d /home/builder/i3-blackarch/.scripts-for-setup ]; then
		cd /home/builder/i3-blackarch/.scripts-for-setup
	else
		printf " \n\nWhere is scripts-for-setup  ? \n\n"
	fi
	echo -en " \n\nThanks for using i3-Setup\n\n ::  Type  startx   to start i3  :: \n\n"  >> /etc/motd
}

PartArt() {														
clear
cat <<"EOT"															

               ...
             ;::::;
           ;::::; :;	DON'T FEAR THE REAPER... 
         ;:::::'   :;        
        ;:::::;     ;.			-={ i3-BlackArch }=-
       ,:::::'       ;           OOO\
       ::::::;       ;          OOOOO\
       ;:::::;       ;         OOOOOOOO
      ,;::::::;     ;'         / OOOOOOO
    ;:::::::::`. ,,,;.        /  / DOOOOOO
  .';:::::::::::::::::;,     /  /     DOOOO
 ,::::::;::::::;;;;::::;,   /  /        DOOO
;`::::::`'::::::;;;::::: ,#/  /          DOOO
:`:::::::`;::::::;;::: ;::#  /            DOOO
::`:::::::`;:::::::: ;::::# /              DOO
`:`:::::::`;:::::: ;::::::#/               DOO
 :::`:::::::`;; ;:::::::::##                OO
 ::::`:::::::`;::::::::;:::#                OO
 `:::::`::::::::::::;'`:;::#                O
  `:::::`::::::::;' /  / `:#
   ::::::`:::::;'  /  /   `#
EOT
sleep 3
}

PartTwo() {
	printf "\033[1m\n    ${red} :: ${green}Lets Do This ${red}::     \n\033[0m"
	pacman -S base-devel vimpager xcompmgr transset-df xorg-server xorg-server-utils rxvt feh xorg-font-util xorg-xinit xterm i3-wm i3status dmenu ttf-dejavu xf86-video-vesa xf86-input-synaptics firefox rxvt-unicode urxvt-perls --noconfirm --needed
	X -configure
	if [ -f "$HOME"/xorg.conf.new ]; then
		mv "$HOME"/xorg.conf.new "$HOME"/xorg.conf
	else
		printf "\n\n where is xorg.conf.new ? -- skipping\n\n"
	fi
	printf "Setting Up i3 config in ~/.i3/config "
	wget https://raw.github.com/BlackArch/i3-blackarch/master/.i3/config
	if [ -f "$HOME"/.i3/config ]; then
		rm -rf ~/.i3
		mkdir ~/.i3
		mv config ~/.i3/config
	else 
		mkdir ~/.i3
		mv config ~/.i3/config
		printf " Things seem fine"
	fi
	printf " \n\nSetting up .zshrc, .Xresources, .vimrc and .xinitrc\n\n"
	wget https://raw.githubusercontent.com/i3-Arch/i3config/master/.zshrc2 -O .zshrc  ##Leaving this to pull from my repo instead of blackarch actually
	wget https://raw.githubusercontent.com/i3-Arch/i3config/master/.xinitrc
	wget https://raw.githubusercontent.com/i3-Arch/i3config/master/.Xresources
	wget https://raw.githubusercontent.com/Blackarch/i3-blackarch/master/i3status.conf
	cp i3status.conf ~/.i3/
	cp .Xresources ~ 
	cp .xinitrc ~
	cp .zshrc ~
	wget https://raw.githubusercontent.com/i3-Arch/i3config/master/ecliz-arch.tar.gz
	tar xzvf ecliz-arch.tar.gz
	rm ecliz-arch.tar.gz
	mv ecliz-arch default
	mv /usr/share/icons/default/ /usr/share/icons/bak-default
	mv default /usr/share/icons/
	printf "\033[1m\n\n ${green}Do you want the default vim config from blackarch ?\n\033[0m"
	printf "\033[1m\n\n ${yellow}Choose ${white}[${red}Y${white}|${green}N${white}]\033[0m"
	printf "\033[1m\nChoose${yellow}'${red}N${yellow}'${yellow} for i3 vim setup \n\n\033[0m"
	printf "\033[1m\n${green}Choice: ${white}\033[0m"
	read OPTION1
	if [ "$OPTION1" == y -o "$OPTION1" == Y ]; then
		printf " \nThats a big 10-4 \n"
	elif [ "$OPTION1" == n -o "$OPTION1" == N ]; then
		rm -rf ~/.vim
		wget https://raw.github.com/t60r/i3-blackarch/master/.vimrc
		cp .vimrc ~/.vimrc
	else
		printf "\n An Error Occured \n\n"
		printf "\n Did you choose 'y'  or 'n' ? \n\n"
	fi

}

HardWare() {
	printf "\033[1m \n\n${green}Are you using intel ?? \033[0m"	
	printf "\033[1m \n ${white}[${green}Y${white}|${red}N${white}] \033[0m"
	printf "\033[1m \n\n${yellow}Answer: ${white}\033[0m"
	read intelstuff
	if [ "$intelstuff" == Y -o "$intelstuff" == y ]; then
		pacman -S intel-dri xf86-video-intel --noconfirm --needed
	else
		printf "\033[1m \n\n ${green}Are you using AMD ? \n\033[0m"
		printf "\033[1m \n ${white}[${green}Y${white}|${red}N${white}] \033[0m"
		printf "\033[1m \n ${yellow}Answer: ${white}\033[0m"
		read amdstuff
		if [ "$amdstuff" == Y -o "$amdstuff" == y ]; then
			pacman -S ati-dri xf86-video-ati --noconfirm --needed
		fi
	fi
}

SetItUp() {
	mkdir "$HOME"/.wallpapers && cd "$HOME"/.wallpapers
	wget https://raw.githubusercontent.com/t60r/blackarch-site/master/images/blackarch-wallpaper-simple.png
	echo "feh --bg-scale '/root/.wallpapers/blackarch-wallpaper-simple.png'" > "$HOME"/.fehbg
	printf "\n\n Downloading and Setting up Official Blackarch Wallpaper in .wallpapers\n\n"
	printf " Never worry about a wallpaper :)    -- This is for i3-blackarch --look in-- '~/.i3/config' " 
	cd "$HOME"
	rm -rf "$HOME"/i3-blackarch
}


BobTheBuilder() {  
		clear
		printf "\033[1m\n\n ${green}Would you like to setup pacaur ? \n\033[0m"
		printf "\033[1m\n\n ${white}It's an ${red}AUR ${white}helper with cower backend \n\n\033[0m"
		printf "\033[1m\n\n${white}[${green}Y${white}|${red}N${white}]\n\n\033[0m"
		printf "\033[1m\n\n${red}Answer: ${white}\033[0m"
		read thatquestion
		if [ "$thatquestion" == Y -o "$thatquestion" == y ]; then
			printf "\033[1m\n\n ${green}Setting up pacaur for future use \n\n\033[0m"
			pacman -Syy expac yajl --noconfirm --needed
			su builder -c "cd /home/builder && mkdir build-dir && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/cower.tar.gz && tar xzvf cower.tar.gz && cd cower && makepkg -s --skippgpcheck --noconfirm"
			pacman -U /home/builder/build-dir/cower/*.xz --noconfirm
			su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/pacaur.tar.gz && tar xzvf pacaur.tar.gz && cd pacaur && makepkg -s --noconfirm"
			pacman -U /home/builder/build-dir/pacaur/*.xz --noconfirm
		else
			printf "\033[1m\n\n ${yellow}You entered no\n\033[0m"
			printf "\033[1m ${yellow}or an unexpected character \n\033[0m"
			printf "\033[1m\n ${red}Moving on... \n\033[0m"
			sleep 2
		fi
}


UrxvtStuff() {
	clear
	printf "\033[1m\n\n${green}Setting up urxvt for custom i3 setup\n\033[0m"
	sleep 2
	if [ ! -d /home/builder/build-dir ]; then
		mkdir /home/builder/build-dir
	fi
	pacman -Syy zsh-syntax-highlighting git xorg-xlsfonts flac  gtk3 json-c libasyncns libnotify libogg libpulse libsndfile libvorbis --noconfirm --needed
	su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/urxvt-tabbedex.tar.gz && tar xzvf urxvt-tabbedex.tar.gz"
	su builder -c "cd /home/builder && cd build-dir/urxvt-tabbedex && makepkg -s --noconfirm"
	pacman -U /home/builder/build-dir/urxvt-tabbedex/*.xz --noconfirm
	su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/oh-my-zsh-git.tar.gz && tar xzvf oh-my-zsh-git.tar.gz"
	su builder -c "cd /home/builder && cd build-dir/oh-my-zsh-git && makepkg -s --noconfirm"
	pacman -U /home/builder/build-dir/oh-my-zsh-git/*.xz --noconfirm
	su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/urxvt-vtwheel.tar.gz && tar xzvf urxvt-vtwheel.tar.gz"
	su builder -c "cd /home/builder && cd build-dir/urxvt-vtwheel && makepkg -s --noconfirm"
	pacman -U /home/builder/build-dir/urxvt-vtwheel/*.xz --noconfirm
	su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/urxvt-font-size-git.tar.gz && tar xzvf urxvt-font-size-git.tar.gz"
	su builder -c "cd /home/builder && cd build-dir/urxvt-font-size-git && makepkg -s	--noconfirm"
	pacman -U /home/builder/build-dir/urxvt-font-size-git/*.xz --noconfirm
	#su builder -c "cd /home/builder && cd build-dir && wget https://aur.archlinux.org/cgit/aur.git/snapshot/prezto-git.tar.gz && tar xzvf prezto-git.tar.gz"
	#su builder -c "cd /home/builder && cd build-dir/prezto-git && makepkg -s --noconfirm"
	#pacman -U /home/builder/build-dir/prezto-git/*.xz --noconfirm 
	userdel -r builder # Remove builder user
	printf "\n\n${green}Changing shell to ${yellow}ZSH\n\n"
	chsh -s $(which zsh)
	cd "$HOME"
}


PartArt2() {
clear
cat <<"EOT"
				TUX IS A BLACKARCHER
                 .88888888:. 
                88888888.88888. 
              .8888888888888888. 
              888888888888888888 
              88' _`88'_  `88888 
              88 88 88 88  88888 
              88_88_::_88_:88888 ~ Sup?
              88:::,::,:::::8888 
              88`:::::::::'`8888 
             .88  `::::'    8:88. 
            8888            `8:888. 
          .8888'             `888888. 
         .8888:..  .::.  ...:'8888888:. 
        .8888.'     :'     `'::`88:88888 
       .8888        '         `.888:8888. 
      888:8     i3  . Archlinux 888:88888 
    .888:88        .:           888:88888: 
    8888888.       ::           88:888888 
    `.::.888.      ::          .88888888 
   .::::::.888.    ::         :::`8888'.:. 
  ::::::::::.888   '         .:::::::::::: 
  ::::::::::::.8    '      .:8::::::::::::. 
 .::::::::::::::.        .:888::::::::::::: 
 :::::::::::::::88:.__..:88888:::::::::::' 
  `'.:::::::::::88888888888.88:::::::::' 
        `':::_:' -- '' -'-' `':_::::'` 
EOT
printf "\033[1m\n\n ${green}TIP ${white}::${red} In the future you will need to Run startx :: \n\n\033[0m"
sleep 3
printf "\033[1m\n\nRebooting now for changes to take effect \n\n\033[0m"
sleep 2
reboot
}

MainThing() {
	FirstThing
	PartOne	
	PartArt
	BobTheBuilder
	PartTwo
	UrxvtStuff
	HardWare
	SetItUp
	PartArt2
}

MainThing

#EOF
