#!/bin/bash
#	THIS IS JUST THE BEGINNING \\ DONT TRIP
# i3-Arch     \\ i3-Blackarch //
#####################################
echo
echo " Lets do this shiiiiiiit " &&
echo
pacman -Syyu &&
sleep 1 &&
rm -rf /usr/share/fonts/* &&
sleep 1 &&
pacman -S base-devel xorg-server xorg-server-utils feh xorg-xinit xterm i3-wm i3status dmenu ttf-dejavu xf86-video-vesa xf86-input-synaptics firefox rxvt-unicode &&
X -configure && sleep 4 &&
mv xorg.conf.new xorg.conf &&
cp /etc/skel/.xinitrc ~ &&  	## Still needs exec i3 + misc things \\ will add later
sleep 1 &&
echo
echo "Setting Up i3 config in ~/.i3/config " &&
echo
wget https://raw.github.com/t60r/i3-blackarch/master/.i3/config &&
sleep 2 &&
mkdir ~/.i3 &&
cp config ~/.i3/config &&
rm config &&
sleep 1 &&
echo
echo " Downloading and Setting up .Xresources & .vimrc " &&
echo
wget https://raw.github.com/t60r/i3-blackarch/master/.Xresources &&
sleep 2 &&
mv .Xresources ~ &&
sleep 1 &&
wget https://raw.github.com/t60r/i3-blackarch/master/.vimrc &&
sleep 2 &&
mv .vimrc ~ && 
exit
